language: node_js
node_js:
  - 10 # user nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  strategy: git
  token: $GH_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
  local_dir: public  
